### ISSUE TITLE
No public key for repo

### ISSUE THREAD

**Issue by donaldinho** [signal18/docs.signal18.io#1]
Been setting this up but there is no public key for the repo which apt-get needs to properly add the repo to the system. Can you provide the public key in the docs?

Although not ideal an alternative is to do this
`deb [trusted=yes arch=amd64] http://repo.signal18.io/deb xenial main`
which turns off authentication just for this repo. Although this is far from ideal could the docs be update to reflect this at the very least?

**Comment by tanji** [comment]
Thanks for reporting, my plan was to provide the public key in the docs but I somehow overlooked that.
